name: Build-and-Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-linux:
    runs-on: ubuntu-latest
    container: fedora:23

    steps:
      - name: wget install
        run: |
          dnf -y install tar git curl fontconfig-devel freetype-devel libX11-xcb libX11-devel
          dnf -y groupinstall "Development Tools" "Development Libraries"
          
      - uses: actions/checkout@v2
      
      

      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Build Release
        run: |
          cargo build --release

      - name: Archive Linux artifact
        run: |
          cd ./target/release/
          strip neovide
          tar czvf neovide.tar.gz neovide

      - uses: actions/upload-artifact@v1
        with:
          name: neovide-linux.tar.gz
          path: ./target/release/neovide.tar.gz
