name: Build-and-Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nightly Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v1

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Install dependencies and neovim
        run: |
          sudo apt-get update
          sudo apt-get -qq install -y \
            curl gnupg ca-certificates git gcc-multilib g++-multilib cmake libssl-dev pkg-config libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev libbz2-dev freeglut3-dev libxi-dev\
            neovim

      - name: Test
        env:
          RUST_BACKTRACE: full
        run: |
          cargo nextest run --profile ci

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: target/nextest/ci/results.xml

      - name: Build Release
        run: |
          cargo build --release

      - name: Archive Linux artifact
        run: |
          cd ./target/release/
          strip neovide
          tar czvf neovide.tar.gz neovide

      - uses: actions/upload-artifact@v1
        with:
          name: neovide-linux.tar.gz
          path: ./target/release/neovide.tar.gz
